Repository Rafael-co/task-aula02-grupo10, pull requests merged in 2023-12, with the labels that each got.

#1 docs: atualização do ReadMe
  README.md
Labels: documentation

#3 add: estilizacao e mais um filme
  index.html
Labels: enhancement

#4 add:assassinos
  README.md
  index.html
Labels: enhancement

#5 add: Senhor dos anéis: O retorno do rei
  index.html
Labels: enhancement

#6 docs: Atualizando README.md
  README.md
Labels: documentation

#7 add:castelo animado
  index.html
Labels: enhancement

#8 Feat add freedy
  README.md
  index.html
Labels: documentation, enhancement

#9 Develop
  README.md
  index.html
Labels: documentation, enhancement

#11 Docs: atualizando README
  README.md
Labels: documentation

#12 Develop -> main
  README.md
Labels: documentation
